### ISSUE TITLE
Read from URL

### ISSUE THREAD

**Issue by aurium** [drmfinlay/tts-util-app#39]
It would be great if I could paste an URL, then it downloads the resource and read it.

This app could register itself as an option to open URLs, opening directly into its "Read URL" mode.

Improvements when mime type is text/html or the extension is html:
- Remove text inside `<script>` or `<style>`, remove all tags `<[^>]*>` and translate `&abc;` occurrences.
- Build a simple navigation menu to read only some part or the page, like text below `<H#>` or inside `<article>`.

**Comment by drmfinlay** [comment]
Hello @aurium,

Thank you for opening this issue.

I think this is a good idea, but it would be quite tricky to implement.  Removing JavaScript, style and other non-textual tags might sound good in theory, but not in practice.  Unfortunately, many modern sites use JavaScript to load text content.  Some sites also require one to login first.

The only reliable way to implement this feature for the modern web would be to interface with a browser, either external or embedded.  I'm afraid that is somewhat beyond my vision for *TTS Util*.

If you really need this feature, Google's [TalkBack app](https://play.google.com/store/apps/details?id=com.google.android.marvin.talkback) should be able to do most of what *TTS Util* could.  *TalkBack* is open source, too.
